// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: content_proto/search_content.proto

package content_proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SearchContentService_Search_FullMethodName = "/searchcontent.SearchContentService/Search"
)

// SearchContentServiceClient is the client API for SearchContentService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SearchContentServiceClient interface {
	Search(ctx context.Context, in *SearchRequest, opts ...grpc.CallOption) (*SearchResponse, error)
}

type searchContentServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSearchContentServiceClient(cc grpc.ClientConnInterface) SearchContentServiceClient {
	return &searchContentServiceClient{cc}
}

func (c *searchContentServiceClient) Search(ctx context.Context, in *SearchRequest, opts ...grpc.CallOption) (*SearchResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SearchResponse)
	err := c.cc.Invoke(ctx, SearchContentService_Search_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SearchContentServiceServer is the server API for SearchContentService service.
// All implementations must embed UnimplementedSearchContentServiceServer
// for forward compatibility.
type SearchContentServiceServer interface {
	Search(context.Context, *SearchRequest) (*SearchResponse, error)
	mustEmbedUnimplementedSearchContentServiceServer()
}

// UnimplementedSearchContentServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSearchContentServiceServer struct{}

func (UnimplementedSearchContentServiceServer) Search(context.Context, *SearchRequest) (*SearchResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Search not implemented")
}
func (UnimplementedSearchContentServiceServer) mustEmbedUnimplementedSearchContentServiceServer() {}
func (UnimplementedSearchContentServiceServer) testEmbeddedByValue()                              {}

// UnsafeSearchContentServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SearchContentServiceServer will
// result in compilation errors.
type UnsafeSearchContentServiceServer interface {
	mustEmbedUnimplementedSearchContentServiceServer()
}

func RegisterSearchContentServiceServer(s grpc.ServiceRegistrar, srv SearchContentServiceServer) {
	// If the following call pancis, it indicates UnimplementedSearchContentServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SearchContentService_ServiceDesc, srv)
}

func _SearchContentService_Search_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SearchContentServiceServer).Search(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SearchContentService_Search_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SearchContentServiceServer).Search(ctx, req.(*SearchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SearchContentService_ServiceDesc is the grpc.ServiceDesc for SearchContentService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SearchContentService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "searchcontent.SearchContentService",
	HandlerType: (*SearchContentServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Search",
			Handler:    _SearchContentService_Search_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "content_proto/search_content.proto",
}
