app:
  env: ${GO_ENV}
  name: ${APP_NAME}
  port: ${PORT}
  url: ${URL}

openSearch:
  url: ${OPENSEARCH_NODE}
  username: ${OPENSEARCH_USERNAME}
  password: ${OPENSEARCH_PASSWORD}
  number_of_shards: ${NUMBER_OF_SHARDS}
  number_of_replicas: ${NUMBER_OF_REPLICAS}

jwt:
  secret_key: ${JWT_SECRET_KEY}
  issuer: ${JWT_ISSUER}
  authorized_apps: ${JWT_AUTHORIZED_APPS}

sentry:
  dsn: ${SENTRY_DSN}
  environment: ${SENTRY_ENVIRONMENT}
  debug: ${SENTRY_DEBUG}

redis:
  host: ${REDIS_HOST}
  port: ${REDIS_PORT}
  password: ${REDIS_PASSWORD}
  db: ${REDIS_DB}

rabbitmq:
  url: ${RABBITMQ_URL}

mongo:
  uri: ${MONGODB_URI}
  database_name: ${DATABASE_NAME}
  content_collection: ${CONTENT_COLLECTION}
  tag_collection: ${TAG_COLLECTION}
  collections_collection: ${COLLECTIONS_COLLECTION}
  content_tags_collection: ${CONTENT_TAGS_COLLECTION}
  content_collections_collection: ${CONTENT_COLLECTIONS_COLLECTION}