app:
  env: ${GO_ENV}
  name: ${APP_NAME}
  port: ${PORT}
  url: ${URL}

sentry:
  dsn: ${SENTRY_DSN}
  environment: ${SENTRY_ENVIRONMENT}

redis:
  host: ${REDIS_HOST}
  port: ${REDIS_PORT}
  password: ${REDIS_PASSWORD}
  db: ${REDIS_DB}

rabbitmq:
  url: ${RABBITMQ_URL}