linters:
  enable:
    - goconst
    - godot
    - gofmt
    - goimports
    - importas
    - whitespace
    - misspell

  disable:
    - depguard
    - nolintlint
    - exhaustruct
    - ireturn
    - wrapcheck
    - err113
    - nlreturn
    - wsl
    - protogetter

  presets:
    - bugs
    - comment
    - complexity
    - error
    - format
    - import
    - metalinter
    - module
    - performance
    - sql
    - style
    - test
    - unused
