# fly.toml app configuration file generated for mfoni-search-service-staging on 2025-01-31T14:38:33Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'mfoni-search-service-staging'
primary_region = 'lhr'

[build]

[experimental]
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0

[[services]]
  internal_port = 8080
  protocol = "tcp"
  [[services.ports]]
    port = "443"
    handlers = ["tls", "http2"]

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
