# fly.toml app configuration file generated for mfoni-search-service-staging on 2025-01-31T14:38:33Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'mfoni-search-service-staging'
primary_region = 'lhr'

[build]

[http_service]
  internal_port = 5001
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
