# fly.toml app configuration file generated for mfoni-search-service-staging on 2025-01-31T14:38:33Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'mfoni-search-service-staging'
primary_region = 'lhr'

[build]

[[services]]
  internal_port = 8080
  protocol = "tcp"
  auto_stop_machines = "stop"
  auto_start_machines = true
  min_machines_running = 0

  [[services.ports]]
    handlers = ["tls"]
    port = 443
    tls_options = { "alpn" = ["h2"] }

  [[services.ports]]
    port = 8080

[services.ports.http_options]
  h2_backend = true

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
