name: Api CI/CD

on:
  push:
    paths:
        - services/main/**
    branches:
      - main
      - prod
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  deploy:
    uses: ./.github/workflows/deploy-api.yml