name: Waitlist CI

on:
  push:
    paths:
      - 'apps/wait-list/**'
    branches:
      - main
      - prod
  pull_request:
    paths:
      - 'apps/wait-list/**'

jobs:
  code-checks:
      name: ⬣ ESLint & ʦ TypeScript
      runs-on: ubuntu-latest
      
      steps:
        - name: ⬇️ Checkout repo
          uses: actions/checkout@v4
  
        - name: ⎔ Setup node
          uses: actions/setup-node@v4
          with:
            node-version: 18
  
        - name: 📥 Download deps
          uses: bahmutov/npm-install@v1
          with:
            working-directory: apps/wait-list
  
        - name: 🔬 Lint
          run: yarn lint
          working-directory: apps/wait-list

        - name: 🔎 Type check
          run: yarn types:check
          working-directory: apps/wait-list
